services:
  penny:
    volumes:
      - ./penny/penny:/penny/penny
      - ./penny/pyproject.toml:/penny/pyproject.toml
      - ./github_api:/shared/github_api:ro
      - ./similarity:/shared/similarity:ro
